CREATE DATABASE realestateagency;


CREATE SCHEMA IF NOT EXISTS Agency;


CREATE TABLE IF NOT EXISTS Agency.PropertyTypes (
    type_id SERIAL PRIMARY KEY,
    type_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Agency.Agents (
    agent_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(15) UNIQUE NOT NULL,
    CONSTRAINT unique_email_phone_agent UNIQUE (email, phone)
);

CREATE TABLE IF NOT EXISTS Agency.Clients (
    client_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    phone VARCHAR(15) UNIQUE NOT NULL,
    CONSTRAINT unique_email_phone_customer UNIQUE (email, phone)
);

CREATE TABLE IF NOT EXISTS Agency.Properties (
    property_id SERIAL PRIMARY KEY,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(100) NOT NULL,
    state VARCHAR(100) NOT NULL,
    zip_code VARCHAR(10) NOT NULL,
    price DECIMAL(15, 2) NOT NULL CHECK (price > 0),
    agent_id BIGINT NOT NULL,
    CONSTRAINT fk_agent FOREIGN KEY (agent_id) REFERENCES Agency.Agents(agent_id)
);

CREATE TABLE IF NOT EXISTS Agency.PropertyDetails (
    property_id BIGINT NOT NULL,
    type_id BIGINT NOT NULL,
    square_footage INT NOT NULL CHECK (square_footage > 0),
    bedrooms INT NOT NULL CHECK (bedrooms >= 0),
    bathrooms INT NOT NULL CHECK (bathrooms >= 0),
    PRIMARY KEY (property_id, type_id),
    CONSTRAINT fk_property FOREIGN KEY (property_id) REFERENCES Agency.Properties(property_id),
    CONSTRAINT fk_type FOREIGN KEY (type_id) REFERENCES Agency.PropertyTypes(type_id)
);

CREATE TABLE IF NOT EXISTS Agency.Transactions (
    transaction_id SERIAL PRIMARY KEY,
    property_id BIGINT NOT NULL,
    client_id BIGINT NOT NULL,
    agent_id BIGINT NOT NULL,
    transaction_date DATE NOT NULL CHECK (transaction_date >= '2024-01-01') DEFAULT CURRENT_DATE,
    amount DECIMAL(15, 2) NOT NULL CHECK (amount > 0),
    CONSTRAINT fk_property FOREIGN KEY (property_id) REFERENCES Agency.Properties(property_id),
    CONSTRAINT fk_client FOREIGN KEY (client_id) REFERENCES Agency.Clients(client_id),
    CONSTRAINT fk_agent FOREIGN KEY (agent_id) REFERENCES Agency.Agents(agent_id)
);


--4. Populate the tables with the sample data generated, ensuring each table has at least 6+ rows (for a total of 36+ rows in all the tables) for the last 3 months.
--Create DML scripts for insert your data. 
--Ensure that the DML scripts do not include values for surrogate keys, as these keys should be generated by the database during runtime. 
--Also, ensure that any DEFAULT values required are specified appropriately in the DML scripts. 
--These DML scripts should be designed to successfully adhere to all previously defined constraints

INSERT INTO Agency.Agents (first_name, last_name, email, phone)
VALUES
    (UPPER('John'), UPPER('Doe'), UPPER('john.doe@example.com'), '123-456-7890'),
    (UPPER('Jane'), UPPER('Smith'), UPPER('jane.smith@example.com'), '098-765-4321'),
    (UPPER('Alice'), UPPER('Johnson'), UPPER('alice.johnson@example.com'), '555-123-4567'),
    (UPPER('Dave'), UPPER('Leaf'), UPPER('dave.leaf@example.com'), '012-735-4121'),
    (UPPER('Michael'), UPPER('Stone'), UPPER('michael.stone@example.com'), '228-745-4221'),
    (UPPER('Kevin'), UPPER('Jefferson'), UPPER('kevin.jefferson@example.com'), '108-745-4331')
ON CONFLICT (email, phone) DO NOTHING;



INSERT INTO Agency.PropertyTypes (type_name)
VALUES
    (UPPER('Apartment')),
    (UPPER('House')),
    (UPPER('Condo')),
    (UPPER('Villa')),
    (UPPER('Townhouse')),
    (UPPER('Duplex'))
ON CONFLICT (type_name) DO NOTHING;


INSERT INTO Agency.Clients (first_name, last_name, email, phone)
VALUES
    (UPPER('Michael'), UPPER('Jordan'), UPPER('michael.jordan@example.com'), '111-222-3333'),
    (UPPER('Emma'), UPPER('Watson'), UPPER('emma.watson@example.com'), '444-555-6666'),
    (UPPER('Robert'), UPPER('Downey'), UPPER('robert.downey@example.com'), '777-888-9999'),
    (UPPER('Chris'), UPPER('Evans'), UPPER('chris.evans@example.com'), '222-333-4444'),
    (UPPER('Scarlett'), UPPER('Johansson'), UPPER('scarlett.johansson@example.com'), '555-666-7777'),
    (UPPER('Tom'), UPPER('Holland'), UPPER('tom.holland@example.com'), '888-999-0000')
ON CONFLICT (email, phone) DO NOTHING;


INSERT INTO Agency.Properties (address, city, state, zip_code, price, agent_id)
SELECT
    vals.address,
    UPPER(vals.city) AS city,
    vals.state,
    vals.zip_code,
    vals.price,
    a.agent_id
FROM (VALUES
    ('101 Pine St', 'Valmiera', 'LV', '4201', 275000, 'john.doe@example.com'),
    ('202 Cedar St', 'Daugavpils', 'LV', '5401', 210000, 'jane.smith@example.com'),
    ('123 Main St', 'Riga', 'LV', '1050', 250000, 'alice.johnson@example.com'),
    ('456 Elm St', 'Jurmala', 'LV', '2015', 300000, 'dave.leaf@example.com'),
    ('789 Oak St', 'Liepaja', 'LV', '3401', 220000, 'michael.stone@example.com'),
    ('303 Maple St', 'Jelgava', 'LV', '3001', 290000, 'kevin.jefferson@example.com')
) AS vals(address, city, state, zip_code, price, agent_email)
JOIN Agency.Agents a ON UPPER(a.email) = UPPER(vals.agent_email)
WHERE NOT EXISTS (
    SELECT 1
    FROM Agency.Properties p
    WHERE p.address = vals.address AND UPPER(p.city) = UPPER(vals.city)
);


-- Insert property details (composite primary key handles conflicts)
INSERT INTO Agency.PropertyDetails (property_id, type_id, square_footage, bedrooms, bathrooms)
SELECT
    p.property_id,
    pt.type_id,
    vals.square_footage,
    vals.bedrooms,
    vals.bathrooms
FROM (VALUES
    ('123 Main St', 'Apartment', 1200, 3, 2),
    ('456 Elm St', 'House', 1500, 4, 3),
    ('789 Oak St', 'Condo', 1000, 2, 2),
    ('101 Pine St', 'Villa', 1800, 5, 4),
    ('202 Cedar St', 'Townhouse', 1300, 3, 2.5),
    ('303 Maple St', 'Duplex', 1600, 4, 3)
) AS vals(address, type_name, square_footage, bedrooms, bathrooms)
JOIN Agency.Properties p ON p.address = vals.address
JOIN Agency.PropertyTypes pt ON UPPER(pt.type_name) = UPPER(vals.type_name)
ON CONFLICT (property_id, type_id) DO NOTHING;

-- Insert transactions (serial primary key handles conflicts)
INSERT INTO Agency.Transactions (property_id, client_id, agent_id, transaction_date, amount)
SELECT
    p.property_id,
    c.client_id,
    a.agent_id,
    vals.transaction_date::date,
    vals.amount
FROM (VALUES
    ('123 Main St', 'michael.jordan@example.com', 'john.doe@example.com', '2025-01-15', 250000),
    ('456 Elm St', 'emma.watson@example.com', 'jane.smith@example.com', '2025-02-20', 300000),
    ('789 Oak St', 'robert.downey@example.com', 'alice.johnson@example.com', '2025-03-10', 220000),
    ('101 Pine St', 'chris.evans@example.com', 'dave.leaf@example.com', '2025-04-05', 275000),
    ('202 Cedar St', 'scarlett.johansson@example.com', 'michael.stone@example.com', '2025-05-12', 210000),
    ('303 Maple St', 'chris.hemsworth@example.com', 'kevin.jefferson@example.com', '2025-06-25', 290000)
) AS vals(property_address, client_email, agent_email, transaction_date, amount)
JOIN Agency.Properties p ON UPPER(p.address) = UPPER(vals.property_address)
JOIN Agency.Clients c ON UPPER(c.email) = UPPER(vals.client_email)
JOIN Agency.Agents a ON UPPER(a.email) = UPPER(vals.agent_email)
WHERE NOT EXISTS (
    SELECT 1
    FROM Agency.Transactions t
    WHERE t.property_id = p.property_id
      AND t.client_id = c.client_id
      AND t.transaction_date = vals.transaction_date::date
);


--5. Create the following functions.
--5.1 Create a function that updates data in one of your tables. This function should take the following input arguments:
--The primary key value of the row you want to update
--The name of the column you want to update
--The new value you want to set for the specified column
--This function should be designed to modify the specified row in the table, updating the specified column with the new value.

CREATE OR REPLACE FUNCTION Agency.update_agent(
    in_agent_id INTEGER,
    in_column_name VARCHAR,
    in_new_value VARCHAR
)
RETURNS VOID AS
$$
BEGIN
    -- Validate that the agent exists
    IF NOT EXISTS (SELECT 1 FROM Agency.Agents WHERE agent_id = in_agent_id) THEN
        RAISE EXCEPTION 'Agent with ID % does not exist', in_agent_id;
    END IF;
    
    -- changes input data to upper (doesent only on phone number)
    IF UPPER(in_column_name) != 'PHONE' THEN
        in_new_value := UPPER(in_new_value);
    END IF;
    
	-- checks 
    IF UPPER(in_column_name) = 'FIRST_NAME' THEN
        UPDATE Agency.Agents 
        SET first_name = in_new_value 
        WHERE agent_id = in_agent_id;
    ELSIF UPPER(in_column_name) = 'LAST_NAME' THEN
        UPDATE Agency.Agents 
        SET last_name = in_new_value 
        WHERE agent_id = in_agent_id;
    ELSIF UPPER(in_column_name) = 'EMAIL' THEN
        UPDATE Agency.Agents 
        SET email = in_new_value 
        WHERE agent_id = in_agent_id;
    ELSIF UPPER(in_column_name) = 'PHONE' THEN
        UPDATE Agency.Agents 
        SET phone = in_new_value  -- Phone remains unchanged case
        WHERE agent_id = in_agent_id;
    ELSE
        RAISE EXCEPTION 'Column "%" does not exist or is not updatable in Agents table', in_column_name;
    END IF;
    
    -- Check if any rows were actually updated
    IF NOT FOUND THEN
        RAISE EXCEPTION 'No rows updated. Value may be the same as existing value';
    END IF;
END;
$$
LANGUAGE plpgsql;

-- test case
SELECT Agency.update_agent(1, 'first_name', 'Joshn');
-- test case 
SELECT Agency.update_agent(1, 'last_name', 's231sd');

-- 5. 2 Create a function that adds a new transaction to your transaction table. 
-- You can define the input arguments and output format. 
-- Make sure all transaction attributes can be set with the function (via their natural keys). 
-- The function does not need to return a value but should confirm the successful insertion of the new transaction.
CREATE OR REPLACE FUNCTION Agency.add_transaction(
    in_property_address TEXT,
    in_client_email TEXT,
    in_agent_email TEXT,
    in_transaction_date DATE,
    in_amount DECIMAL
) RETURNS VOID AS $$
DECLARE
    v_property_id BIGINT;
    v_client_id BIGINT;
    v_agent_id BIGINT;
    v_transaction_exists BOOLEAN;
BEGIN

    SELECT p.property_id INTO v_property_id
    FROM Agency.Properties p
    WHERE p.address = in_property_address;


    SELECT c.client_id INTO v_client_id
    FROM Agency.Clients c
    WHERE UPPER(c.email) = UPPER(in_client_email);

    SELECT a.agent_id INTO v_agent_id
    FROM Agency.Agents a
    WHERE UPPER(a.email) = UPPER(in_agent_email);

    SELECT EXISTS (
        SELECT 1 
        FROM Agency.Transactions 
        WHERE property_id = v_property_id 
          AND client_id = v_client_id 
          AND agent_id = v_agent_id 
          AND transaction_date = in_transaction_date
          AND amount = in_amount
    ) INTO v_transaction_exists;

    IF v_transaction_exists THEN
        RAISE NOTICE 'Transaction already exists in the database.';
    ELSE
        -- insert new transaction
        INSERT INTO Agency.Transactions (property_id, client_id, agent_id, transaction_date, amount)
        VALUES (v_property_id, v_client_id, v_agent_id, add_transaction.in_transaction_date, add_transaction.in_amount);

        -- success confirmation
        RAISE NOTICE 'New transaction added successfully.';
    END IF;
END;
$$ LANGUAGE plpgsql;

-- test case 
SELECT Agency.add_transaction(
    '123 Main St',
    'emma.watson@example.com',
    'john.doe@example.com',
    CURRENT_DATE,
    250000
);

--test case
SELECT Agency.add_transaction(
    '789 Oak St',
    'emma.watson@example.com',
    'john.doe@example.com',
    CURRENT_DATE,
    250000
);




--6. Create a view that presents analytics for the most recently added quarter in your database. Ensure that the result excludes irrelevant fields such as surrogate keys and duplicate entries.
CREATE OR REPLACE VIEW Agency.RecentQuarterAnalytics AS
SELECT
    T.transaction_date,
    P.address,
    P.city,
    P.state,
    P.zip_code,
    P.price,
    A.first_name AS agent_first_name,
    A.last_name AS agent_last_name,
    C.first_name AS client_first_name,
    C.last_name AS client_last_name,
    T.amount
FROM
    Agency.Transactions T
JOIN
    Agency.Properties P ON T.property_id = P.property_id
JOIN
    Agency.Agents A ON T.agent_id = A.agent_id
JOIN
    Agency.Clients C ON T.client_id = C.client_id
WHERE
    T.transaction_date >= CURRENT_DATE - INTERVAL '3 months';

--test case
SELECT * FROM Agency.RecentQuarterAnalytics;


--7. Create a read-only role for the manager. This role should have permission to perform SELECT queries on the database tables, and also be able to log in. Please ensure that you adhere to best practices for database security when defining this role
CREATE ROLE manager_read_only WITH
    LOGIN
    PASSWORD 'password';  

-- connection / schema permissions
GRANT CONNECT ON DATABASE realestateagency TO manager_read_only;
GRANT USAGE ON SCHEMA Agency TO manager_read_only;

-- select for tables add_transaction and quarteranalytics
GRANT SELECT ON ALL TABLES IN SCHEMA Agency TO manager_read_only;
GRANT EXECUTE ON FUNCTION Agency.add_transaction(
    TEXT,  -- property_address
    TEXT,  -- client_email
    TEXT,  -- agent_email
    DATE,  -- transaction_date
    DECIMAL  -- amount
) TO manager_read_only;
GRANT SELECT ON TABLE Agency.RecentQuarterAnalytics TO manager_read_only;
